version: '3.9'
services:
  db:
    image: "postgres:14.5"
    container_name: feature-toggle-service-db
    restart: always
    environment:
      POSTGRES_USER: featureToggleServiceDbUser
      POSTGRES_PASSWORD: featureToggleServiceDbPassword
      POSTGRES_DB: featureToggleServiceDb
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]